### ISSUE TITLE
Please release as NPM package

### ISSUE THREAD

**Issue by szyablitsky** [kamranahmedse/jquery-toast-plugin#9]
Thank you )

**Comment by kamranahmedse** [comment]
Will do. Thanks

**Comment by istrau3** [comment]
I would also like to get this from npm. If not uploading to npm (or at least for the meantime), it would be great if you could just add a package.json (as npm can get directly from github). Currently when I try:

```javascript
npm install kamranahmedse/jquery-toast-plugin --save
```
I get thrown an error that is related to the absence of package.json.

Really like the plugin...

**Comment by kamranahmedse** [comment]
Totally forgot about the issue. Expect it today.

**Comment by kamranahmedse** [comment]
Just released it, try: `npm install jquery-toast-plugin`

**Comment by istrau3** [comment]
@kamranahmedse I just tried it. I am getting a webpack build error now that is related to the "main" entry in package.json. Any way you can change the following in package.json:

```javascript
"main": "jquery.toast.js"
```

to read either:

```javascript
"main": "dist/jquery.toast.min.js"
```
or
```javascript
"main": "src/jquery.toast.js"
```

basically, to point to an existing file (something in webpack, not sure if it is webpack itself or one of the loaders, scans all the node_modules and indexes their main files and it is erroring out because jquery.toast.js does not exist in the root of jquery-toast-plugin).

**Comment by kamranahmedse** [comment]
Hey @istrau3 thank your for reporting that. Could you please try again? I just fixed that.

**Comment by istrau3** [comment]
@kamranahmedse Looks to be working well now. Thanks a lot.
